// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/common.proto

package com.su.proto;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrorRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ErrorResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string errorCode = 1;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <code>string errorCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <code>string errorMsg = 2;</code>
     */
    java.lang.String getErrorMsg();
    /**
     * <code>string errorMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();

    /**
     * <code>repeated string parameters = 3;</code>
     */
    java.util.List<java.lang.String>
        getParametersList();
    /**
     * <code>repeated string parameters = 3;</code>
     */
    int getParametersCount();
    /**
     * <code>repeated string parameters = 3;</code>
     */
    java.lang.String getParameters(int index);
    /**
     * <code>repeated string parameters = 3;</code>
     */
    com.google.protobuf.ByteString
        getParametersBytes(int index);
  }
  /**
   * <pre>
   * 错误提示
   * </pre>
   *
   * Protobuf type {@code ErrorResp}
   */
  public  static final class ErrorResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ErrorResp)
      ErrorRespOrBuilder {
    // Use ErrorResp.newBuilder() to construct.
    private ErrorResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorResp() {
      errorCode_ = "";
      errorMsg_ = "";
      parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ErrorResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              errorCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                parameters_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              parameters_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          parameters_ = parameters_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.proto.CommonProto.internal_static_ErrorResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.proto.CommonProto.internal_static_ErrorResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.proto.CommonProto.ErrorResp.class, com.su.proto.CommonProto.ErrorResp.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object errorCode_;
    /**
     * <code>string errorCode = 1;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      }
    }
    /**
     * <code>string errorCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorMsg_;
    /**
     * <code>string errorMsg = 2;</code>
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string errorMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList parameters_;
    /**
     * <code>repeated string parameters = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getParametersList() {
      return parameters_;
    }
    /**
     * <code>repeated string parameters = 3;</code>
     */
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <code>repeated string parameters = 3;</code>
     */
    public java.lang.String getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <code>repeated string parameters = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParametersBytes(int index) {
      return parameters_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getErrorCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMsg_);
      }
      for (int i = 0; i < parameters_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parameters_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getErrorCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMsg_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameters_.size(); i++) {
          dataSize += computeStringSizeNoTag(parameters_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParametersList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.proto.CommonProto.ErrorResp)) {
        return super.equals(obj);
      }
      com.su.proto.CommonProto.ErrorResp other = (com.su.proto.CommonProto.ErrorResp) obj;

      boolean result = true;
      result = result && getErrorCode()
          .equals(other.getErrorCode());
      result = result && getErrorMsg()
          .equals(other.getErrorMsg());
      result = result && getParametersList()
          .equals(other.getParametersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode().hashCode();
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
      if (getParametersCount() > 0) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getParametersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.proto.CommonProto.ErrorResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.proto.CommonProto.ErrorResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.proto.CommonProto.ErrorResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.proto.CommonProto.ErrorResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.proto.CommonProto.ErrorResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.proto.CommonProto.ErrorResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.proto.CommonProto.ErrorResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.proto.CommonProto.ErrorResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.proto.CommonProto.ErrorResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.proto.CommonProto.ErrorResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.proto.CommonProto.ErrorResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 错误提示
     * </pre>
     *
     * Protobuf type {@code ErrorResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ErrorResp)
        com.su.proto.CommonProto.ErrorRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.proto.CommonProto.internal_static_ErrorResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.proto.CommonProto.internal_static_ErrorResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.proto.CommonProto.ErrorResp.class, com.su.proto.CommonProto.ErrorResp.Builder.class);
      }

      // Construct using com.su.proto.CommonProto.ErrorResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = "";

        errorMsg_ = "";

        parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.proto.CommonProto.internal_static_ErrorResp_descriptor;
      }

      public com.su.proto.CommonProto.ErrorResp getDefaultInstanceForType() {
        return com.su.proto.CommonProto.ErrorResp.getDefaultInstance();
      }

      public com.su.proto.CommonProto.ErrorResp build() {
        com.su.proto.CommonProto.ErrorResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.proto.CommonProto.ErrorResp buildPartial() {
        com.su.proto.CommonProto.ErrorResp result = new com.su.proto.CommonProto.ErrorResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.errorCode_ = errorCode_;
        result.errorMsg_ = errorMsg_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          parameters_ = parameters_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parameters_ = parameters_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.proto.CommonProto.ErrorResp) {
          return mergeFrom((com.su.proto.CommonProto.ErrorResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.proto.CommonProto.ErrorResp other) {
        if (other == com.su.proto.CommonProto.ErrorResp.getDefaultInstance()) return this;
        if (!other.getErrorCode().isEmpty()) {
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.proto.CommonProto.ErrorResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.proto.CommonProto.ErrorResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object errorCode_ = "";
      /**
       * <code>string errorCode = 1;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMsg_ = "";
      /**
       * <code>string errorMsg = 2;</code>
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorMsg = 2;</code>
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorMsg = 2;</code>
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string errorMsg = 2;</code>
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParametersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          parameters_ = new com.google.protobuf.LazyStringArrayList(parameters_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getParametersList() {
        return parameters_.getUnmodifiableView();
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public int getParametersCount() {
        return parameters_.size();
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public java.lang.String getParameters(int index) {
        return parameters_.get(index);
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParametersBytes(int index) {
        return parameters_.getByteString(index);
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public Builder setParameters(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public Builder addParameters(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public Builder addAllParameters(
          java.lang.Iterable<java.lang.String> values) {
        ensureParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameters_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public Builder clearParameters() {
        parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 3;</code>
       */
      public Builder addParametersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ErrorResp)
    }

    // @@protoc_insertion_point(class_scope:ErrorResp)
    private static final com.su.proto.CommonProto.ErrorResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.proto.CommonProto.ErrorResp();
    }

    public static com.su.proto.CommonProto.ErrorResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorResp>
        PARSER = new com.google.protobuf.AbstractParser<ErrorResp>() {
      public ErrorResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorResp> getParserForType() {
      return PARSER;
    }

    public com.su.proto.CommonProto.ErrorResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/common.proto\"D\n\tErrorResp\022\021\n\terr" +
      "orCode\030\001 \001(\t\022\020\n\010errorMsg\030\002 \001(\t\022\022\n\nparame" +
      "ters\030\003 \003(\tB\033\n\014com.su.protoB\013CommonProtob" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ErrorResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErrorResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorResp_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMsg", "Parameters", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
